# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SharkKMeansTrain <- function(X, k) {
    .Call('SharkPack_SharkKMeansTrain', PACKAGE = 'SharkPack', X, k)
}

SharkKMeansPredict <- function(X, centroids) {
    .Call('SharkPack_SharkKMeansPredict', PACKAGE = 'SharkPack', X, centroids)
}

