// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SharkKMeansTrain
List SharkKMeansTrain(NumericMatrix X, ssize_t k);
RcppExport SEXP SharkPack_SharkKMeansTrain(SEXP XSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< ssize_t >::type k(kSEXP);
    __result = Rcpp::wrap(SharkKMeansTrain(X, k));
    return __result;
END_RCPP
}
// SharkKMeansPredict
List SharkKMeansPredict(NumericMatrix X, NumericMatrix centroids);
RcppExport SEXP SharkPack_SharkKMeansPredict(SEXP XSEXP, SEXP centroidsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type centroids(centroidsSEXP);
    __result = Rcpp::wrap(SharkKMeansPredict(X, centroids));
    return __result;
END_RCPP
}
