# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kolmogorov-Smirnov test
#'
#' Compares marginal and conditional probability density function for a given
#' subspace slice.
#'
#' @param indexSelection Logical vector that describes the subspace slice on
#'   the data set. A random subspace slice can be genearted by \code{\link{randomSubspaceSliceC}}.
#' @param indexMapReferenceAttribute Index vector for the data objects ordered by the
#'   reference dimension. Each entry of the vector contains the index to the
#'   initial data set. The index is starting with 1.
#' @return double Supremum of the absolute distance between the marginal and
#'   conditional distribution of the reference attribute.
#' @seealso \code{\link{randomSubspaceSliceC}}, \code{\link{sortedIndexMatrix}}
#' @export
KSTestC <- function(indexSelection, indexMapReferenceAttribute) {
    .Call('subcon_KSTestC', PACKAGE = 'subcon', indexSelection, indexMapReferenceAttribute)
}

#' Random selection of a subspace slice
#'
#' Creates conditions for all dimensions of a given subspace and a given
#' reference dimension. Subspace selection is not done on the data set but
#' rather on the pre calculated index map.
#'
#' @param indexMap Index matrix (see \code{\link{sortedIndexMatrix}}) for the data objects if ordered by
#'   dimension. Each entry of the vector contains the index to the
#'   initial data set. The index is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions. Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice (expected value).
#' @param referenceDim Reference attribute upon which the conditions for the slice will be set.
#' @return Logical Vector indicating which data objects remain in the subspace slice.
#' @seealso \code{\link{sortedIndexMatrix}}
#' @export
randomSubspaceSliceC <- function(indexMap, subspace, alpha, referenceDim) {
    .Call('subcon_randomSubspaceSliceC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim)
}

#' Deviation
#'
#' Average deviation over random subspace slices for a given reference
#' attribute.
#'
#' @param indexMap Index matrix (see \code{\link{sortedIndexMatrix}}) for the
#'   data objects if ordered by dimension. Each entry of the vector contains
#'   the index to the initial data set. The index is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions.
#'   Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param referenceDim Reference attribute upon which the conditions for the
#'   slice will be set.
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return double, the deviation for the reference dimension.
#' @seealso \code{\link{sortedIndexMatrix}}
#' @export
averageDeviationC <- function(indexMap, subspace, alpha, referenceDim, numRuns) {
    .Call('subcon_averageDeviationC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim, numRuns)
}

deviationVectorC <- function(indexMap, subspace, alpha, referenceDim, numRuns) {
    .Call('subcon_deviationVectorC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim, numRuns)
}

deviationStatisticsC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_deviationStatisticsC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

#' HiCS contrast
#'
#' Calculates the HiCS contrast for a given subspace.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions.
#'   Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return double, the HiCS contrast for the subspace.
#' @export
HiCSContrastC <- function(indexMap, subspace, alpha, numRuns) {
    .Call('subcon_HiCSContrastC', PACKAGE = 'subcon', indexMap, subspace, alpha, numRuns)
}

#' Deviation matrix
#'
#' Calculates the deviation for all 2-dimensional projections of the full
#' space.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return NumericMatrix with deviations where the row is the reference
#'   attribute, column the conditional attribute of the 2-dimensional subspace.
#'   This matrix is asymmetric in general.
#' @export
deviationMatrixC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_deviationMatrixC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

#' HiCS matrix
#'
#' Calculates the HiCS contrast for all 2-dimensional projections of the full
#' space.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return Symmetric NumericMatrix with HiCS contrast that is the average
#'   deviation when the reference dimension is selected randomly.
#' @export
HiCSMatrixC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_HiCSMatrixC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

