# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kolmogorov-Smirnov test
#'
#' Compares marginal and conditional probability density function for a given
#' subspace slice.
#'
#' @param indexSelection Logical vector that describes the subspace slice on
#'   the data set. A random subspace slice can be genearted by \code{\link{randomSubspaceSliceC}}.
#' @param indexMapReferenceAttribute Index vector for the data objects ordered by the
#'   reference dimension. Each entry of the vector contains the index to the
#'   initial data set. The index is starting with 1.
#' @return double Supremum of the absolute distance between the marginal and
#'   conditional distribution of the reference attribute.
#' @seealso \code{\link{randomSubspaceSliceC}}, \code{\link{sortedIndexMatrix}}
#' @export
KSTestC <- function(indexSelection, indexMapReferenceAttribute) {
    .Call('subcon_KSTestC', PACKAGE = 'subcon', indexSelection, indexMapReferenceAttribute)
}

#' Random selection of a subspace slice
#'
#' Creates conditions for all dimensions of a given subspace and a given
#' reference dimension. Subspace selection is not done on the data set but
#' rather on the pre calculated index map.
#'
#' @param indexMap Index matrix (see \code{\link{sortedIndexMatrix}}) for the data objects if ordered by
#'   dimension. Each entry of the vector contains the index to the
#'   initial data set. The index is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions. Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice (expected value).
#' @param referenceDim Reference attribute upon which the conditions for the slice will be set.
#' @return Logical Vector indicating which data objects remain in the subspace slice.
#' @seealso \code{\link{sortedIndexMatrix}}
#' @export
randomSubspaceSliceC <- function(indexMap, subspace, alpha, referenceDim) {
    .Call('subcon_randomSubspaceSliceC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim)
}

#' Deviation
#'
#' Average deviation over random subspace slices for a given reference
#' attribute.
#'
#' @param indexMap Index matrix (see \code{\link{sortedIndexMatrix}}) for the
#'   data objects if ordered by dimension. Each entry of the vector contains
#'   the index to the initial data set. The index is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions.
#'   Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param referenceDim Reference attribute upon which the conditions for the
#'   slice will be set.
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return double, the deviation for the reference dimension.
#' @seealso \code{\link{sortedIndexMatrix}}
#' @export
averageDeviationC <- function(indexMap, subspace, alpha, referenceDim, numRuns) {
    .Call('subcon_averageDeviationC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim, numRuns)
}

deviationVectorC <- function(indexMap, subspace, alpha, referenceDim, numRuns) {
    .Call('subcon_deviationVectorC', PACKAGE = 'subcon', indexMap, subspace, alpha, referenceDim, numRuns)
}

deviationStatisticsC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_deviationStatisticsC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

#' HiCS contrast
#'
#' Calculates the HiCS contrast for a given subspace.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param subspace Numerical vector consisting of the subspace dimensions.
#'   Index for dimensions starts with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return double, the HiCS contrast for the subspace.
#' @export
HiCSContrastC <- function(indexMap, subspace, alpha, numRuns) {
    .Call('subcon_HiCSContrastC', PACKAGE = 'subcon', indexMap, subspace, alpha, numRuns)
}

#' Deviation matrix
#'
#' Calculates the deviation for all 2-dimensional projections of the full
#' space.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return NumericMatrix with deviations where the row is the reference
#'   attribute, column the conditional attribute of the 2-dimensional subspace.
#'   This matrix is asymmetric in general.
#' @export
deviationMatrixC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_deviationMatrixC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

#' HiCS matrix
#'
#' Calculates the HiCS contrast for all 2-dimensional projections of the full
#' space.
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return Symmetric NumericMatrix with HiCS contrast that is the average
#'   deviation when the reference dimension is selected randomly.
#' @export
HiCSMatrixC <- function(indexMap, alpha, numRuns) {
    .Call('subcon_HiCSMatrixC', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

#' HiCS Search
#'
#' HiCS search following the apriori search scheme. The implementation is
#' according to the original publication and inspired by the nim-implemtation
#' \url{https://github.com/bluenote10/HiCS}.
#'
#' @param Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   subspace contrast.
#' @param topkSearch top-k contrast subspaces in the search beam.
#' @param topkOutput top-k contrast subspaces in the final output.
#'
#'@return List of
#'\item{subspaces}{List of top-k final subspaces ordered by contrast.}
#'\item{contrast}{Vector of contrast values of the top-k final subspaces.}
#' @seealso \code{\link{HiCSContrastC}}, \code{\link{sortedIndexMatrix}}
#'
#' @references Keller, Fabian, Emmanuel Muller, and Klemens Bohm. 2012. HiCS:
#'   High Contrast Subspaces for Density-Based Outlier Ranking. In 2012 IEEE
#'   28th International Conference on Data Engineering, 1037 – 48. IEEE.
#'
#' @export
HiCSSearch <- function(indexMap, alpha, numRuns, topkSearch, topkOutput) {
    .Call('subcon_HiCSSearch', PACKAGE = 'subcon', indexMap, alpha, numRuns, topkSearch, topkOutput)
}

#' LOF reachability distance
#'
#' Calculates reachability distance for all objects
#'
#' @param knnIndex n x k Matrix of knn indices
#' @param knnDistance n x k Matrix of knn distances
#' @param vector indices for the k-neighborhood
#' @return vector of local reachability densities
#'
#' @export
reachability <- function(knnIndex, knnDistance, maxkIdx) {
    .Call('subcon_reachability', PACKAGE = 'subcon', knnIndex, knnDistance, maxkIdx)
}

#' Local outlier factor calculation
#'
#' Calculates LOF based on reachability densitiesfor all objects
#'
#' @param lrd vector of local reachability densities
#' @param knnIndex n x k Matrix of knn indices
#' @param vector indices for the k-neighborhood
#' @return vector of local outlier factors
#'
#' @export
lofCalculation <- function(lrd, knnIndex, maxkIdx) {
    .Call('subcon_lofCalculation', PACKAGE = 'subcon', lrd, knnIndex, maxkIdx)
}

#' Greedy Maximum Deviation  Heuristic
#'
#' Constructs one deviation maximizing subspace for each dimension. The search
#' is based on the two dimensional deviations. For each dimension r, the
#' heuristic orders the two dimensional projections [r, s_i] by deviation, with
#' s_i being the conditional attribute. The search starts with the highest two
#' dimensional projection as the initial subspace. The next candidate to be
#' added to that subspace is the dimension that has the second highest
#' deviation. If the deviation for r increases by adding a dimension, the
#' subspace will be updated, else that dimension is discarded.
#'
#' Examples
#'
#' reference dimension: 1
#' 2-dim projections (ordered by deviation):
#' [1,3] deviation(1|3) = 0.6
#' [1,2] deviation(1|2) = 0.5
#' [1,5] deviation(1|5) = 0.4
#' [1,4] deviation(1|4) = 0.3
#'
#' Initial subspace: [1,3]
#'
#' add dimension 2
#' [1,2,3] deviation(1|2,3) = 0.65 -> increases the deviation for the reference dimension
#'
#' add dimension 5
#' [1,2,3,5] deviation(1|2,3) = 0.62 -> decreases the deviation for the reference dimension
#'
#' add dimension 5
#' [1,2,3,5] deviation(1|2,3,5) = 0.62 -> decreases the deviation for the reference dimension
#'
#' add dimension 4
#' [1,2,3,4] deviation(1|2,3,4) = 0.67 -> increases the deviation for the reference dimension
#'
#' Output space for reference dimension 1: [1,2,3,4]
#'
#'
#' @param indexMap Index for the data objects if ordered by dimension. Each
#'   entry of the vector contains the index to the initial data set. The index
#'   is starting with 1.
#' @param alpha Percentage of data objects to remain in the subspace slice
#'   (expected value).
#' @param numRuns number of random subspace slices used to estimate the
#'   deviation.
#' @return List of deviation maximizing subspaces, one for each reference dimension.
#' @export
GMD <- function(indexMap, alpha, numRuns) {
    .Call('subcon_GMD', PACKAGE = 'subcon', indexMap, alpha, numRuns)
}

